- https://discord.com/developers/applications/880719898987335681/information
- https://github.com/5310/discord-bot-aleister
- https://vercel.com/scio/discord-bot-aleister
- https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type
- https://discord.com/developers/docs/interactions/receiving-and-responding
- https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure
- https://canary.discord.com/developers/docs/interactions/slash-commands#registering-a-command
- https://discord.com/developers/docs/topics/oauth2
- 